FROM node:22-bookworm-slim

# Instalamos dependencias del sistema de una vez
RUN apt-get update && apt-get install -y \
    openssl \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Instalamos el Sonar Scanner CLI de forma global
RUN npm install -g sonar-scanner

# Verificamos que tenga permisos de ejecución
RUN chmod +x /usr/local/bin/sonar-scanner

USER node